spring:
  application:
    name: ghostnetfishing
  datasource:
    url: jdbc:mysql://localhost:3307/ghostnet_test
    username: spring-user-prod
    password: spring-password-prod
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true #TODO: false setzen f√ºr LazyLoadingOption?